fixtures:
  repositories:
    "apt":
      "repo": "git://github.com/puppetlabs/puppetlabs-apt.git"
      "ref": "1.8.0"
    "stdlib":
      "repo": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      "ref": "v2.2.1"
  symlinks:
    "opsmatic": "#{source_dir}"
